In [1]:
pip install transformers

In [2]:
from transformers import pipeline

In [3]:
import transformers
print(transformers.__version__)

4.53.2


In [4]:
import librosa
import torch
import IPython.display as ipd
import numpy as np
from transformers import Wav2Vec2ForCTC, Wav2Vec2Tokenizer


In [9]:
tokenizer=Wav2Vec2Tokenizer.from_pretrained("facebook/wav2vec2-base-960h")
model=Wav2Vec2ForCTC.from_pretrained("facebook/wav2vec2-base-960h")
audio,sampling_rate=librosa.load("output.mp3",sr=16000)
audio,sampling_rate

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/163 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/291 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/85.0 [00:00<?, ?B/s]

config.json: 0.00B [00:00, ?B/s]

The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'Wav2Vec2CTCTokenizer'. 
The class this function is called from is 'Wav2Vec2Tokenizer'.
/usr/local/lib/python3.11/dist-packages/transformers/models/wav2vec2/tokenization_wav2vec2.py:720: FutureWarning: The class `Wav2Vec2Tokenizer` is deprecated and will be removed in version 5 of Transformers. Please use `Wav2Vec2Processor` or `Wav2Vec2CTCTokenizer` instead.
  warnings.warn(


model.safetensors:   0%|          | 0.00/378M [00:00<?, ?B/s]

Some weights of Wav2Vec2ForCTC were not initialized from the model checkpoint at facebook/wav2vec2-base-960h and are newly initialized: ['wav2vec2.masked_spec_embed']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


(array([ 1.9539925e-14,  7.1054274e-15, -4.8849813e-14, ...,
        -1.4222499e-07, -5.8098470e-07,  3.3810312e-07], dtype=float32),
 16000)

In [12]:
import IPython.display as ipd
ipd.Audio(audio, rate=sampling_rate, autoplay=True)

In [16]:
input_values=tokenizer(audio,return_tensors="pt").input_values
input_values


tensor([[0.0005, 0.0005, 0.0005,  ..., 0.0005, 0.0005, 0.0005]])

In [17]:
logits=model(input_values).logits
logits


tensor([[[ 14.2067, -26.8231, -26.5293,  ...,  -6.4899,  -8.3348,  -7.2419],
         [ 14.1717, -26.7800, -26.4892,  ...,  -6.4459,  -8.3040,  -7.2327],
         [ 13.7933, -25.5070, -25.2313,  ...,  -6.0287,  -7.6817,  -6.9809],
         ...,
         [ 13.8077, -24.3493, -24.0602,  ...,  -4.4481,  -7.1437,  -5.6616],
         [ 13.7937, -24.4980, -24.2069,  ...,  -4.5899,  -7.2000,  -5.8585],
         [ 13.8081, -24.3519, -24.0627,  ...,  -4.4489,  -7.1464,  -5.6615]]],
       grad_fn=<ViewBackward0>)

In [18]:
predicted_ids=torch.argmax(logits,dim=-1)
transcription=tokenizer.decode(predicted_ids[0])
transcription

'THIS AUDIOPHILE IS SAVED TO MYGUGAL DRIVE'